main = "./dist/worker.mjs"
compatibility_date = "2025-03-10"
workers_dev = false # Enable it for development purposes, and if you are want a domain ending with .workers.dev
account_id = "022362f27de5264a50ce60cb23293c9f" # Log in dash.cloudflare.com, select an account, go to Workers, and copy Account ID

[build]
command = "npm install && npm run build"

[env.production]
name = "act-issuer-production"
route = { pattern = "act-issuer.research.cloudflare.com", custom_domain = true }

[env.production.triggers]
crons = ["0 0 * * *"]

[env.production.vars]
DIRECTORY_CACHE_MAX_AGE_SECONDS = "86400"
ENVIRONMENT = "production"
KEY_LIFESPAN_IN_MS = "172800000" # 48h
KEY_NOT_BEFORE_DELAY_IN_MS = "7200000" # 2h
MINIMUM_FRESHEST_KEYS = "1"
ROTATION_CRON_STRING = "30 12 * * *"
SENTRY_SAMPLE_RATE = "0" # Between 0-1 if you log errors on Sentry. 0 disables Sentry logging. Configuration is done through Workers Secrets
SERVICE = "act-issuer-production"
# ACT configuration
ACT_DOMAIN_SEPARATOR = "act-issuer.research.cloudflare.com"
ACT_L = "8" # Supports balances 0-255

[[env.production.r2_buckets]]
bucket_name = 'act-issuer-keys-production' # wrangler r2 bucket create act-issuer-keys-production
preview_bucket_name = 'act-issuer-keys-production-local'
binding = 'ISSUANCE_KEYS'

[[env.production.r2_buckets]]
bucket_name = 'act-issuer-act-keys-production' # wrangler r2 bucket create act-issuer-act-keys-production
preview_bucket_name = 'act-issuer-act-keys-production-local'
binding = 'ACT_ISSUANCE_KEYS'

[env.production.version_metadata]
binding = "VERSION_METADATA"

[[env.production.workflows]]
name = "key-backup-workflow"
binding = "KEY_BACKUP_WF"
class_name = "KeyBackupWorkflow"
